// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXIH3R8fhfmHof8GxWHnT9Lqoag8gw7JQ',
    appId: '1:1038522757895:web:26abe3d80e824c1a80cba2',
    messagingSenderId: '1038522757895',
    projectId: 'photopoet-ebtw5',
    authDomain: 'photopoet-ebtw5.firebaseapp.com',
    storageBucket: 'photopoet-ebtw5.firebasestorage.app',
    measurementId: 'G-9RFTVR3BMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeNjQX_0OHU1BZNNLNVCBkdjzc_Y3_m-E',
    appId: '1:1038522757895:android:986c86065b072c6680cba2',
    messagingSenderId: '1038522757895',
    projectId: 'photopoet-ebtw5',
    storageBucket: 'photopoet-ebtw5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2sJFWqwOja41Kd7rb1lyJhyuV9X_JAAE',
    appId: '1:1038522757895:ios:fe069bee54b4203b80cba2',
    messagingSenderId: '1038522757895',
    projectId: 'photopoet-ebtw5',
    storageBucket: 'photopoet-ebtw5.firebasestorage.app',
    iosBundleId: 'com.example.photoPoet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-K0J9PhrLwpWvynW6AtNFpfbw_fMamPg',
    appId: '1:1038522757895:web:785167d97bdd6c6980cba2',
    messagingSenderId: '1038522757895',
    projectId: 'photopoet-ebtw5',
    authDomain: 'photopoet-ebtw5.firebaseapp.com',
    storageBucket: 'photopoet-ebtw5.firebasestorage.app',
    measurementId: 'G-MQW4TEGLY3',
  );
}
